/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const ZodiacSign = IDL.Nat;
export const Ratings = IDL.Record({
  'happiness' : IDL.Nat,
  'good' : IDL.Nat,
  'love' : IDL.Nat,
  'luck' : IDL.Nat,
  'overall' : IDL.Nat,
});

export const idlService = IDL.Service({
  'getAllQuotations' : IDL.Func(
      [],
      [IDL.Vec(IDL.Tuple(ZodiacSign, IDL.Opt(IDL.Text)))],
      ['query'],
    ),
  'getAllRatings' : IDL.Func(
      [],
      [IDL.Vec(IDL.Tuple(ZodiacSign, IDL.Opt(Ratings)))],
      ['query'],
    ),
  'getQuotation' : IDL.Func([ZodiacSign], [IDL.Opt(IDL.Text)], ['query']),
  'getRatings' : IDL.Func([ZodiacSign], [IDL.Opt(Ratings)], ['query']),
  'setQuotation' : IDL.Func([ZodiacSign, IDL.Text], [], []),
  'setRatings' : IDL.Func(
      [ZodiacSign, IDL.Nat, IDL.Nat, IDL.Nat, IDL.Nat, IDL.Nat],
      [],
      [],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const ZodiacSign = IDL.Nat;
  const Ratings = IDL.Record({
    'happiness' : IDL.Nat,
    'good' : IDL.Nat,
    'love' : IDL.Nat,
    'luck' : IDL.Nat,
    'overall' : IDL.Nat,
  });
  
  return IDL.Service({
    'getAllQuotations' : IDL.Func(
        [],
        [IDL.Vec(IDL.Tuple(ZodiacSign, IDL.Opt(IDL.Text)))],
        ['query'],
      ),
    'getAllRatings' : IDL.Func(
        [],
        [IDL.Vec(IDL.Tuple(ZodiacSign, IDL.Opt(Ratings)))],
        ['query'],
      ),
    'getQuotation' : IDL.Func([ZodiacSign], [IDL.Opt(IDL.Text)], ['query']),
    'getRatings' : IDL.Func([ZodiacSign], [IDL.Opt(Ratings)], ['query']),
    'setQuotation' : IDL.Func([ZodiacSign, IDL.Text], [], []),
    'setRatings' : IDL.Func(
        [ZodiacSign, IDL.Nat, IDL.Nat, IDL.Nat, IDL.Nat, IDL.Nat],
        [],
        [],
      ),
  });
};

export const init = ({ IDL }) => { return []; };