/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Ratings {
  'happiness' : bigint,
  'good' : bigint,
  'love' : bigint,
  'luck' : bigint,
  'overall' : bigint,
}
export type ZodiacSign = bigint;
export interface _SERVICE {
  'getAllQuotations' : ActorMethod<[], Array<[ZodiacSign, [] | [string]]>>,
  'getAllRatings' : ActorMethod<[], Array<[ZodiacSign, [] | [Ratings]]>>,
  'getQuotation' : ActorMethod<[ZodiacSign], [] | [string]>,
  'getRatings' : ActorMethod<[ZodiacSign], [] | [Ratings]>,
  'setQuotation' : ActorMethod<[ZodiacSign, string], undefined>,
  'setRatings' : ActorMethod<
    [ZodiacSign, bigint, bigint, bigint, bigint, bigint],
    undefined
  >,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];